# 数据库连接信息
spring:
    datasource:
        # 驱动类名称
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 数据库连接的URL
        #        url: jdbc:mysql://localhost:3306/javaweb_schema?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        url: jdbc:mysql://localhost:3306/javaweb_schema?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        # 用户名
        #        username: healthuser
        username: root
        # 密码
        #        password: healthuser@1234
        password: 123456
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1

# MyBatis Plus配置信息
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true # 开启mybatis驼峰命名自动映射
    type-aliases-package: com.example.entity
    mapper-locations: classpath*:/mapper/**/*.xml

#mybatis:
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#        map-underscore-to-camel-case: true # 开启mybatis驼峰命名自动映射


server:
    port: 9000
    tomcat:
        max-http-form-post-size: -1